// mod day1;
// mod day2;
// mod day3;
// mod day4;
// mod day5;
// mod day6;
// mod day7;
// mod day8;
// mod day9;
// mod day10;
// mod day11;
// mod day12;
mod day16;
mod utils;
extern crate regex;
extern crate crypto;

fn main() {
	// day1::part1::run();
	// day1::part2::run();
	// day2::part1::run();
	// day2::part2::run();
	// day3::part1::run();
	// day3::part2::run();
	// day4::part1::run();
	// day4::part2::run();
	// day5::part1::run();
	// day5::part2::run();
	// day6::part1::run();
	// day6::part2::run();
	// day7::part1::run();
	// day7::part2::run();
	// day8::part1::run();
	// day8::part2::run();
	// day9::part1::run();
	// day9::part2::run();
	// day10::run();
	// day11::part1::run();
	// day11::part2::run();
	// day12::part1::run();
	// day12::part2::run();
	day16::part1::run();
	day16::part2::run();
}